### ISSUE TITLE
Pulling http headers out of the context?

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [encoredev/encore#37] opened 2021-05-27 13:26 UTC
Is there a "encore" way to pull arbitrary http headers out of the context?

**Comment by eandre** [comment] 2021-06-13 14:35
Hey @MatthewJamesBoyle, I missed when you posted this issue so apologies for the delayed response.

There's currently no way of accessing arbitrary HTTP headers when using structured Encore APIs. This is currently by design, as when you rely on HTTP headers Encore loses the ability to reason about what data is needed to call an API. That said, it would be great to understand your use case and we can see if there's a good way of supporting what you're trying to do.

Note that you can always access HTTP headers by defining a `raw` endpoint (which is the "escape hatch" we provide for doing things like this).

**Comment by eandre** [comment] 2021-06-22 07:58
Closing this as it's by design (use `raw` endpoints if you need an escape hatch). That said, would love to hear more about your use case if possible!

**Closed by eandre** 2021-06-22 07:58 UTC
