### ISSUE TITLE
Minor issues with Hello World tutorial example

### ISSUE THREAD

**Issue by TobbeEdgeware** [encoredev/encore#99] opened 2021-09-29 10:26 UTC
When I did git push encore on the hello world example I got the output remote: 

`Env Dashboard: https://app.encore.dev/test2-ave2/env/prod`

 but that link gives a “500 Internal Server Error response”. The code is pushed and works though.
 
 A minute thing is that the tutorial documentation says that the development server is starting on port 4000, but it is 4060 (or 4061 if 4060 is occupied).

**Comment by eandre** [comment] 2021-09-29 11:44
Thanks @TobbeEdgeware for the report! I suspect the issue is actually that you're not logged in, and we've had some issues with the login detection that have been tricky to detect. Can you head over to https://app.encore.dev and check if you're prompted to log in? Will have another look at fixing the login detection.

As for the port, this is actually something we just changed (see #94) to make the port a bit easier to remember. If you update to the latest release (`encore version update`) it should start your app on port 4000.

**Comment by eandre** [comment] 2021-09-29 19:27
I've tested this and believe the login detection should be fixed. Thanks for the report! Please reopen if this turns out not to be the case :)

**Closed by eandre** 2021-09-29 19:27 UTC
